/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-station-3-a7a6ad10261149cab31aa394bfcf8940
Title: Space Station 3
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

// type GLTFResult = GLTF & {
//   nodes: {
//     Object_4: THREE.Mesh
//     Object_6: THREE.Mesh
//     Object_8: THREE.Mesh
//     Object_10: THREE.Mesh
//     Object_12: THREE.Mesh
//     Object_14: THREE.Mesh
//     Object_16: THREE.Mesh
//     Object_18: THREE.Mesh
//   }
//   materials: {
//     spacestation_main2: THREE.MeshPhysicalMaterial
//     spacestation_smalllights: THREE.MeshPhysicalMaterial
//     spacestation_main: THREE.MeshPhysicalMaterial
//   }
// }

// type ActionName = 'Animation'
// type GLTFActions = Record<ActionName, THREE.AnimationAction>

export const SpaceStation = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/space_station_3.glb')
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions && actions.Animation) {
      actions.Animation.reset().fadeIn(0.5).play()
    }

    return () => {
      if (actions && actions.Animation) {
        actions.Animation.fadeOut(0.5)
      }
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-2.04380502, -0.21349001, -0.06103325]}
          scale={[2.70079637, 2.70079636, 2.7007963]}
          userData={{ name: 'Sketchfab_model' }}>
          <group name="root" userData={{ name: 'root' }}>
            <group
              name="GLTF_SceneRootNode"
              rotation={[Math.PI / 2, 0, 0]}
              userData={{ name: 'GLTF_SceneRootNode' }}>
              <group name="SpaceStation_low_0" userData={{ name: 'SpaceStation_low_0' }}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.spacestation_main2}
                  userData={{ name: 'Object_4' }}
                />
              </group>
              <group name="SpaceStation001_low_1" userData={{ name: 'SpaceStation.001_low_1' }}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.spacestation_smalllights}
                  userData={{ name: 'Object_6' }}
                />
              </group>
              <group name="SpaceStation002_low_2" userData={{ name: 'SpaceStation.002_low_2' }}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.spacestation_main2}
                  userData={{ name: 'Object_8' }}
                />
              </group>
              <group name="SpaceStation003_low_3" userData={{ name: 'SpaceStation.003_low_3' }}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.spacestation_main2}
                  userData={{ name: 'Object_10' }}
                />
              </group>
              <group name="SpaceStation004_low_4" userData={{ name: 'SpaceStation.004_low_4' }}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.spacestation_main}
                  userData={{ name: 'Object_12' }}
                />
              </group>
              <group name="SpaceStation005_low_5" userData={{ name: 'SpaceStation.005_low_5' }}>
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.spacestation_main}
                  userData={{ name: 'Object_14' }}
                />
              </group>
              <group
                name="SpaceStation006_low_6"
                rotation={[Math.PI, -0.54462781, Math.PI]}
                userData={{ name: 'SpaceStation.006_low_6' }}>
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.spacestation_main}
                  userData={{ name: 'Object_16' }}
                />
              </group>
              <group name="SpaceStation007_low_7" userData={{ name: 'SpaceStation.007_low_7' }}>
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.spacestation_main}
                  userData={{ name: 'Object_18' }}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/space_station_3.glb')
